### ISSUE TITLE
Ubuntu 22 support

### ISSUE THREAD

**Issue by the-crypt-keeper** [kalavai-net/kalavai-client#22]
Using the curl | sh installer on Ubuntu 22.04.4 LTS does not produce a working installation:

```
$ kalavai start
[172787] Error loading Python lib '/tmp/_MEIQjapai/libpython3.12.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIQjapai/libpython3.12.so.1.0)
```

It's python 3.10.12 and gcc 11.4.0 on this OS.

**Comment by musoles** [comment]
@the-crypt-keeper thanks for reporting this issue.

This was due to an undue high requirement on GCC lib. I've rebuilt the releases to work with older Ubuntu versions.

Could you retest?

1. Delete your current kalavai installation

`sudo apt remove kalavai -y`

2. Reinstall normally

`curl -sfL https://raw.githubusercontent.com/kalavai-net/kalavai-client/main/assets/install_client.sh | bash -`

**Comment by the-crypt-keeper** [comment]
Confirmed fixed, thanks for the quick turn around!
